
spring:
  application:
    name: springboot-activiti
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/activiti?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123321
  activiti:
    check-process-definitions: true



server:
  port: 9090

mybatis:
  mybatis.type-aliases-package: com.activiti.bean